version: '3.2'
services:
  prometheus:
    image: "prom/prometheus:v2.26.0"
    ports:
    - "9090:9090"
    volumes:
    - type: bind
      source: ./compose/prometheus.yml
      target: /etc/prometheus/prometheus.yml
  grafana:
    image: "grafana/grafana:7.5.3"
    ports:
    - "3000:3000"
