name: Build

on: push

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
    - name: Setup clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2021.04.23'

    - name: Check out Git repository
      uses: actions/checkout@v2.3.4

    - name: Lint
      run: make lint

  test:
    needs: [ lint ]

    strategy:
      matrix:
        module:
        - async
        - coll
        - cql
        - db
        - db-resource-store
        - db-resource-store-cassandra
        - db-tx-log
        - db-tx-log-kafka
        - executor
        - extern-terminology-service
        - fhir-client
        - fhir-path
        - fhir-structure
        - http-client
        - interaction
        - kv
        - luid
        - openid-auth
        - operation-measure-evaluate-measure
        - rest-api
        - rest-util
        - scheduler
        - search-param-registry

        java-version:
        - '11'
        - '15'

    runs-on: ubuntu-20.04

    steps:
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java-version }}

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        tools-deps: '1.10.3.822'

    - name: Cache Local Maven Repo
      uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-${{ matrix.java-version }}-maven-repo-test-${{ matrix.module }}

    - name: Check out Git repository
      uses: actions/checkout@v2.3.4

    - name: Test
      run: make -C modules/${{ matrix.module }} test

  test-coverage:
    needs: [ test ]

    strategy:
      matrix:
        module:
        - async
        - coll
        - cql
        - db
        - db-resource-store
        - db-resource-store-cassandra
        - db-tx-log
        - db-tx-log-kafka
        - executor
        - extern-terminology-service
        - fhir-client
        - fhir-path
        - fhir-structure
        - http-client
        - interaction
        - kv
        - luid
        - openid-auth
        - operation-measure-evaluate-measure
        - rest-api
        - rest-util
        - scheduler
        - search-param-registry

    runs-on: ubuntu-20.04

    steps:
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        tools-deps: '1.10.3.822'

    - name: Cache Local Maven Repo
      uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-${{ matrix.java-version }}-maven-repo-test-coverage-${{ matrix.module }}

    - name: Check out Git repository
      uses: actions/checkout@v2.3.4

    - name: Test Coverage
      run: make -C modules/${{ matrix.module }} test-coverage

    - name: Codecov Upload
      uses: codecov/codecov-action@master
      with:
        name: ${{ matrix.module }}
        file: modules/${{ matrix.module }}/target/coverage/codecov.json
        fail_ci_if_error: true

  test-root:
    needs: [ lint ]

    strategy:
      matrix:
        java-version:
        - '11'
        - '15'

    runs-on: ubuntu-20.04

    steps:
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java-version }}

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        tools-deps: '1.10.3.822'

    - name: Cache Local Maven Repo
      uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-${{ matrix.java-version }}-maven-repo-test-root

    - name: Check out Git repository
      uses: actions/checkout@v2.3.4

    - name: Test
      run: make test-root

  build:
    needs: [ test, test-root ]
    runs-on: ubuntu-20.04

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/samply/blaze:${{ github.sha }}

    - name: Scan Container Image
      uses: azure/container-scan@v0
      with:
        image-name: ghcr.io/samply/blaze:${{ github.sha }}

  integration-test:
    needs: build
    runs-on: ubuntu-20.04

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Pull Docker Image
      run: docker pull ghcr.io/samply/blaze:${{ github.sha }}

    - name: Run Blaze
      run: docker run --name blaze --rm -d -e JAVA_TOOL_OPTIONS=-Xmx2g -p 8080:8080 -v blaze-data:/app/data ghcr.io/samply/blaze:${{ github.sha }}

    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11

    - name: Download Synthea
      run: curl -sLO https://github.com/synthetichealth/synthea/releases/download/v2.7.0/synthea-with-dependencies.jar

    - name: Generate Data
      run: java -jar synthea-with-dependencies.jar -p 100

    - name: Install Blazectl
      run: .github/scripts/install-blazectl.sh

    - name: Docker Logs
      run: docker logs blaze

    - name: Check Capability Statement
      run: .github/scripts/check-capability-statement.sh

    - name: Load Data
      run: ./blazectl --server http://localhost:8080/fhir upload output/fhir

    - name: Count Resources
      run: ./blazectl --server http://localhost:8080/fhir count-resources

    - name: Download Patient Resources
      run: .github/scripts/download-resources.sh Patient

    - name: Download Patient Resources - Including Observation, Condition, Encounter and Procedure
      run: .github/scripts/revinclude.sh

    - name: Download Observation Resources
      run: .github/scripts/download-resources.sh Observation

    - name: Download Observation Resources - Including Patients
      run: ./blazectl --server http://localhost:8080/fhir download -t Observation -q '_include=Observation:patient' -o Observation-Patient.ndjson

    - name: Download Observation Resources - Including Encounters and Patients
      run: ./blazectl --server http://localhost:8080/fhir download -t Observation -q '_include=Observation:encounter&_include=Observation:patient' -o Observation-Encounter-Patient.ndjson

    - name: Download Observation Resources - Including Encounters and Encounter Patients
      run: ./blazectl --server http://localhost:8080/fhir download -t Observation -q '_include=Observation:encounter&_include:iterate=Encounter:patient' -o Observation-Encounter-Encounter-Patient.ndjson

    - name: Download Condition Resources
      run: .github/scripts/download-resources.sh Condition

    - name: Download Condition Resources - Including Subjects
      run: ./blazectl --server http://localhost:8080/fhir download -t Condition -q '_include=Condition:subject' -o Condition-Subject.ndjson

    - name: Download Condition Resources - Including Encounters
      run: ./blazectl --server http://localhost:8080/fhir download -t Condition -q '_include=Condition:encounter' -o Condition-Encounter.ndjson

    - name: Download DiagnosticReport Resources
      run: .github/scripts/download-resources.sh DiagnosticReport

    - name: Download MedicationRequest Resources - Including Medications
      run: ./blazectl --server http://localhost:8080/fhir download -t MedicationRequest -q '_include=MedicationRequest:medication' -o MedicationRequest.ndjson

    - name: Evaluate CQL Query 1
      run: ./evaluate-measure.sh -f modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q1-query.cql http://localhost:8080/fhir

    - name: Evaluate CQL Query 2
      run: ./evaluate-measure.sh -f modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q2-query.cql http://localhost:8080/fhir

    - name: Evaluate CQL Query 7
      run: ./evaluate-measure.sh -f modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q7-query.cql http://localhost:8080/fhir

    - name: Evaluate CQL Query 14
      run: ./evaluate-measure.sh -f modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q14-query.cql http://localhost:8080/fhir

    - name: Evaluate CQL Query 15
      run: ./evaluate-measure.sh -f modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q15-query.cql http://localhost:8080/fhir

    - name: Docker Stop
      run: docker stop blaze

  openid-auth-test:
    needs: build
    runs-on: ubuntu-20.04

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Run Keycloak and Blaze
      run: docker-compose -f .github/openid-auth-test/docker-compose.yml up -d

    - name: Sleep 90s
      run: sleep 90

    - name: Docker Logs Keycloak
      run: docker-compose -f .github/openid-auth-test/docker-compose.yml logs keycloak

    - name: Docker Logs Blaze
      run: docker-compose -f .github/openid-auth-test/docker-compose.yml logs blaze

    - name: Unauthenticated Request
      run: test "MSG_AUTH_REQUIRED" = "$(curl -s http://localhost:8080/fhir | jq -r .issue[0].details.coding[0].code)"

    - name: Authenticated Request
      run: .github/scripts/authenticated-request.sh
